# Generated by Django 6.0.6 on 2026-06-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='slug',
            field=models.SlugField(default='Linux', unique=True),
            preserve_default=False,
        ),
    ]
