# Generated by Django 6.0.6 on 2026-06-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor'), ('administrador', 'Administrador')], default='alumno', max_length=20),
        ),
    ]
