"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(
    BASE_DIR / '.env'
)
print("DB_USER =", os.getenv("DB_USER"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django_bootstrap5',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'usuarios',
    'profesores',
    'cursos',
    'matriculas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        # Configuración de la base de datos por defecto en Django

        'ENGINE': 'django.db.backends.postgresql',
        # Motor de base de datos que se va a utilizar (PostgreSQL en este caso)

        'NAME': os.getenv(
            'DB_NAME'
        ),
        # Nombre de la base de datos (se obtiene desde el archivo .env)

        'USER': os.getenv(
            'DB_USER'
        ),
        # Usuario de PostgreSQL que se usa para conectarse a la base de datos

        'PASSWORD': os.getenv(
            'DB_PASSWORD'
        ),
        # Contraseña del usuario de la base de datos (también viene del .env)

        'HOST': os.getenv(
            'DB_HOST'
        ),
        # Dirección del servidor donde está la base de datos
        # 'localhost' si está en el mismo ordenador

        'PORT': os.getenv(
            'DB_PORT'
        ),
        # Puerto de conexión a PostgreSQL (por defecto 5432)
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
# URL pública desde la que Django sirve los archivos subidos por el usuario (imágenes, documentos, etc.)
# Ejemplo: /media/profesores/foto.jpg

MEDIA_ROOT = BASE_DIR / 'media'
# Ruta física en el proyecto donde se guardan realmente los archivos subidos
# Ejemplo: gestion_formacion/media/

LOGIN_REDIRECT_URL = '/'
# Página a la que se redirige el usuario después de iniciar sesión correctamente

LOGOUT_REDIRECT_URL = '/'
# Página a la que se redirige el usuario después de cerrar sesión

AUTH_USER_MODEL = 'usuarios.Usuario'
# Indica a Django que el modelo de usuario por defecto será el modelo personalizado
# que ya has creado dentro de la aplicación "usuarios"

# 'usuarios' → es el nombre de la app donde ya tienes definido tu models.py
# 'Usuario' → es la clase del modelo dentro de ese models.py que hereda de AbstractUser

# Esto hace que Django use tu modelo Usuario en todo el sistema de autenticación
# en lugar del modelo por defecto (auth.User)
# IMPORTANTE: debe estar definido desde el inicio del proyecto antes de hacer migraciones

JAZZMIN_SETTINGS = {
    "site_title": "Gestión Formación",
    "site_header": "Gestión Formación",
    "site_brand": "Academia",
    "welcome_sign": "Bienvenido al panel",
    "show_sidebar": True,
    "navigation_expanded": True,
}